"""Adds network_type table

Revision ID: 5f118b507d55
Revises: 8f5130b5b415
Create Date: 2017-04-12 10:45:27.147164

"""
from alembic import op
import sqlalchemy as sa
from app.data.initial_data_network_types import initial_network_types
from json import loads


# revision identifiers, used by Alembic.
revision = '5f118b507d55'
down_revision = '8f5130b5b415'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    network_type_table = op.create_table('network_type',
                                         sa.Column('id', sa.Integer(), nullable=False),
                                         sa.Column('name', sa.String(length=10), nullable=True),
                                         sa.Column('type', sa.String(length=5), nullable=True),
                                         sa.PrimaryKeyConstraint('id'),
                                         sa.UniqueConstraint('id')
                                         )
    network_types = loads(initial_network_types)['network_types']
    op.bulk_insert(network_type_table, network_types)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('network_type')
    # ### end Alembic commands ###



